/*
 * Copyright (C) 2023 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.strata.valuation;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.joda.beans.impl.direct.DirectPrivateBeanBuilder;

import com.google.common.collect.ImmutableList;
import com.opengamma.strata.calc.CalculationRules;
import com.opengamma.strata.calc.Column;

/**
 * Control parameters for valuation.
 * <p>
 * This class holds the parameters needed to control the valuation process.
 * It includes the valuation date-time, the columns to calculate, and the calculation rules.
 */
@BeanDefinition(builderScope = "private")
public final class Control implements ImmutableBean {

  /**
   * The valuation date-time.
   */
  @PropertyDefinition(validate = "notNull")
  private final ZonedDateTime valuationDateTime;

  /**
   * The columns to calculate.
   */
  @PropertyDefinition(validate = "notNull")
  private final ImmutableList<Column> columns;

  /**
   * The calculation rules.
   */
  @PropertyDefinition(validate = "notNull")
  private final CalculationRules calculationRules;

  //------------------------- AUTOGENERATED START -------------------------
  /**
   * The meta-bean for {@code Control}.
   * @return the meta-bean, not null
   */
  public static Control.Meta meta() {
    return Control.Meta.INSTANCE;
  }

  static {
    MetaBean.register(Control.Meta.INSTANCE);
  }

  private Control(
      ZonedDateTime valuationDateTime,
      List<Column> columns,
      CalculationRules calculationRules) {
    JodaBeanUtils.notNull(valuationDateTime, "valuationDateTime");
    JodaBeanUtils.notNull(columns, "columns");
    JodaBeanUtils.notNull(calculationRules, "calculationRules");
    this.valuationDateTime = valuationDateTime;
    this.columns = ImmutableList.copyOf(columns);
    this.calculationRules = calculationRules;
  }

  @Override
  public Control.Meta metaBean() {
    return Control.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the valuation date-time.
   * @return the value of the property, not null
   */
  public ZonedDateTime getValuationDateTime() {
    return valuationDateTime;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the columns to calculate.
   * @return the value of the property, not null
   */
  public ImmutableList<Column> getColumns() {
    return columns;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the calculation rules.
   * @return the value of the property, not null
   */
  public CalculationRules getCalculationRules() {
    return calculationRules;
  }

  //-----------------------------------------------------------------------
  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      Control other = (Control) obj;
      return JodaBeanUtils.equal(valuationDateTime, other.valuationDateTime) &&
          JodaBeanUtils.equal(columns, other.columns) &&
          JodaBeanUtils.equal(calculationRules, other.calculationRules);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(valuationDateTime);
    hash = hash * 31 + JodaBeanUtils.hashCode(columns);
    hash = hash * 31 + JodaBeanUtils.hashCode(calculationRules);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(128);
    buf.append("Control{");
    buf.append("valuationDateTime").append('=').append(JodaBeanUtils.toString(valuationDateTime)).append(',').append(' ');
    buf.append("columns").append('=').append(JodaBeanUtils.toString(columns)).append(',').append(' ');
    buf.append("calculationRules").append('=').append(JodaBeanUtils.toString(calculationRules));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code Control}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code valuationDateTime} property.
     */
    private final MetaProperty<ZonedDateTime> valuationDateTime = DirectMetaProperty.ofImmutable(
        this, "valuationDateTime", Control.class, ZonedDateTime.class);
    /**
     * The meta-property for the {@code columns} property.
     */
    @SuppressWarnings({"unchecked", "rawtypes" })
    private final MetaProperty<ImmutableList<Column>> columns = DirectMetaProperty.ofImmutable(
        this, "columns", Control.class, (Class) ImmutableList.class);
    /**
     * The meta-property for the {@code calculationRules} property.
     */
    private final MetaProperty<CalculationRules> calculationRules = DirectMetaProperty.ofImmutable(
        this, "calculationRules", Control.class, CalculationRules.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "valuationDateTime",
        "columns",
        "calculationRules");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -949589828:  // valuationDateTime
          return valuationDateTime;
        case 949721053:  // columns
          return columns;
        case -1452505282:  // calculationRules
          return calculationRules;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends Control> builder() {
      return new Control.Builder();
    }

    @Override
    public Class<? extends Control> beanType() {
      return Control.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code valuationDateTime} property.
     * @return the meta-property, not null
     */
    public MetaProperty<ZonedDateTime> valuationDateTime() {
      return valuationDateTime;
    }

    /**
     * The meta-property for the {@code columns} property.
     * @return the meta-property, not null
     */
    public MetaProperty<ImmutableList<Column>> columns() {
      return columns;
    }

    /**
     * The meta-property for the {@code calculationRules} property.
     * @return the meta-property, not null
     */
    public MetaProperty<CalculationRules> calculationRules() {
      return calculationRules;
    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code Control}.
     */
    private static final class Builder extends DirectPrivateBeanBuilder<Control> {

      private ZonedDateTime valuationDateTime;
      private List<Column> columns = ImmutableList.of();
      private CalculationRules calculationRules;

      /**
       * Restricted constructor.
       */
      private Builder() {
      }

      //-----------------------------------------------------------------------
      @Override
      public Object get(String propertyName) {
        switch (propertyName.hashCode()) {
          case -949589828:  // valuationDateTime
            return valuationDateTime;
          case 949721053:  // columns
            return columns;
          case -1452505282:  // calculationRules
            return calculationRules;
          default:
            throw new NoSuchElementException("Unknown property: " + propertyName);
        }
      }

      @SuppressWarnings("unchecked")
      @Override
      public Builder set(String propertyName, Object newValue) {
        switch (propertyName.hashCode()) {
          case -949589828:  // valuationDateTime
            this.valuationDateTime = (ZonedDateTime) newValue;
            break;
          case 949721053:  // columns
            this.columns = (List<Column>) newValue;
            break;
          case -1452505282:  // calculationRules
            this.calculationRules = (CalculationRules) newValue;
            break;
          default:
            throw new NoSuchElementException("Unknown property: " + propertyName);
        }
        return this;
      }

      @Override
      public Control build() {
        return new Control(
            valuationDateTime,
            columns,
            calculationRules);
      }
    }

    //-----------------------------------------------------------------------
    /**
     * The serialization version id.
     */
    private static final long serialVersionUID = 1L;
  }
  //-------------------------- AUTOGENERATED END --------------------------
}
